name: Build & Publish PRODUCTION (pull-based)

on:
  push:
    tags:
      - PRODUCTION

permissions:
  contents: write


jobs:
  build-and-release:
    if: github.ref == 'refs/tags/PRODUCTION'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build (Maven) im Unterordner
        working-directory: servlets/heimautomatisierung.heating-orchestrator
        run: mvn -B -DskipTests package

      - name: Artefakt finden
        id: findjar
        working-directory: servlets/heimautomatisierung.heating-orchestrator
        run: |
          jar=$(ls -1 target/*-SNAPSHOT.jar 2>/dev/null || true)
          if [ -z "$jar" ]; then jar=$(ls -1 target/*.jar | head -n1); fi
          echo "jar=$jar" >> $GITHUB_OUTPUT

      - name: Artefakte vorbereiten
        run: |
          mkdir -p dist
          cp "servlets/heimautomatisierung.heating-orchestrator/${{ steps.findjar.outputs.jar }}" dist/heating-orchestrator.jar
          (cd dist && shasum -a 256 app.jar | awk '{print $1}') > dist/heating-orchestrator.jar.sha256

      - name: Release @ PRODUCTION aktualisieren
        uses: softprops/action-gh-release@v2
        with:
          tag_name: PRODUCTION
          name: PRODUCTION
          body: "Automated build for PRODUCTION"
          files: |
            dist/heating-orchestrator.jar
            dist/heating-orchestrator.jar.sha256
